### ISSUE TITLE
Mixed Content Error when frontend uses HTTPS

### ISSUE THREAD

**Issue by milouk** [unmade/shelf-showcase#12]
I have deployed the app behind traefik and issued an ssl certificate for the frontend. My API_BASE_URL is set to `http://shelf-back:8000`. Since fontend has https and backend is http I am getting a "Mixed Content" error. Is there a way to have the frontend using https while the backend is http?

My docker compose is as follows:

```
  shelf-back:
    container_name: shelf-back
    image: fdooch/shelf-back:0.1.0-alpha.11
    env_file:
      - ./shelf/shelf.env
    volumes:
      - ./certs:/usr/src/shelf-back/certs
      - ./shelf-data:/usr/src/shelf-data
    depends_on:
      - redis
      - edgedb
    ports:
      - "8000:80"
    networks:
      private-network:
        ipv4_address: 10.1.0.22


  shelf-worker:
    container_name: shelf-worker
    image: fdooch/shelf-back:0.1.0-alpha.11
    env_file:
      - ./shelf/shelf.env
    volumes:
      - ./certs:/usr/src/shelf-back/certs
      - ./shelf-data:/usr/src/shelf-data
    command: ["celery", "-A", "app.tasks", "worker", "-l", "INFO"]
    depends_on:
      - edgedb
      - redis
    networks:
      private-network:
        ipv4_address: 10.1.0.23

  shelf-front:
    container_name: shelf-front
    image: fdooch/shelf-front:0.1.0-alpha.12
    env_file:
      - ./shelf/shelf.env
    depends_on:
      - shelf-back
    networks:
      private-network:
        ipv4_address: 10.1.0.24
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.services.shelf.loadbalancer.server.port=80
      - traefik.http.routers.shelf-https.entrypoints=https
      - traefik.http.routers.shelf-https.rule=Host(`shelf.example.org`)
      - traefik.http.routers.shelf-https.tls=true
      - traefik.http.routers.shelf-https.tls.certresolver=le
      - traefik.http.routers.shelf-https.middlewares=chain-middlewares-no-auth@file

  edgedb:
    container_name: edgedb
    image: edgedb/edgedb:2.5
    env_file:
      - ./shelf/shelf.env
    volumes:
      - dbvolume:/var/lib/edgedb/data
      - ./certs:/certs
    ports:
      - "5656:5656"
    networks:
      private-network:
        ipv4_address: 10.1.0.25
    labels:
      - com.centurylinklabs.watchtower.enable=true
   ```
