### ISSUE TITLE
Support for ARM?

### ISSUE THREAD

**Issue by heryoff** [unmade/shelf-showcase#4]

**Comment by unmade** [comment]
hey @heryoff 

Are you talking about arm32 (raspberry pi) or arm64? 

The project uses EdgeDB which currently provides only amd64 docker images, but since version EdgeDB 2.0 it should be possible to build your own arm64 docker image.

I'm also interested in ARM, because I'm developing on Apple Silicon, so it is on my map, just not the first priority.

If you want try the project you can check out the [cloud version](https://getshelf.cloud), it is the same as the docker one

**Comment by heryoff** [comment]
> hey @heryoff
> 
> Are you talking about arm32 (raspberry pi) or arm64?
> 
> The project uses EdgeDB which currently provides only amd64 docker images, but since version EdgeDB 2.0 it should be possible to build your own arm64 docker image.
> 
> I'm also interested in ARM, because I'm developing on Apple Silicon, so it is on my map, just not the first priority.
> 
> If you want try the project you can check out the [cloud version](https://getshelf.cloud), it is the same as the docker one

Yes I'm mainly taking about arm64, even tho arm32 could probably work too. 
I'll try the cloud version, thanks

**Comment by unmade** [comment]
I've just pushed arm64 images, feel free to check

**Comment by heryoff** [comment]
Hey, I was trying to test stuff out but I still get "exec format error", can you explain how to select the arm image?

**Comment by unmade** [comment]
It should be selected automatically. I checked images on two different machines (with M1 and M1 Pro chips), but I can't checked it on raspberry pi, as I don't have it.

Can you please provide the whole error log you're seeing? Is it happening on pulling stage or when containers starting to run?

**Comment by heryoff** [comment]
Ok I managed to make it work by clearing out the images, thanks

**Comment by heryoff** [comment]
Mmm, I still get "something went wrong" when trying to log-in

**Comment by unmade** [comment]
You can try changing `API_BASE_URL` in the `docker-compose.yml` and set it to `http://ip-of-your-container:8000`. 
In the `.shelf-back.env` set `CORS_ALLOW_ORIGINS` to the `http://ip-of-your-container:8080` or you can set it `*`

**Comment by heryoff** [comment]
Still can't make it work, :(

**Comment by heryoff** [comment]
Docker-compose file
```
services:
  shelf-back:
    image: fdooch/shelf-back:0.1.0-alpha.6
    env_file:
      - ./shelf-back.env
    environment:
      - SHELF_SUPERUSER_USERNAME=admin
      - SHELF_SUPERUSER_PASSWORD=root
    volumes:
      - ./certs:/usr/src/shelf-back/certs
      - ./shelf-data:/usr/src/shelf-data
    ports:
      - "8001:80"
    depends_on:
      - redis
      - edgedb

  shelf-worker:
    image: fdooch/shelf-back:0.1.0-alpha.6
    env_file:
      - ./shelf-back.env
    volumes:
      - ./certs:/usr/src/shelf-back/certs
      - ./shelf-data:/usr/src/shelf-data
    command: ["celery", "-A", "app.tasks", "worker", "-l", "INFO"]
    depends_on:
      - edgedb
      - redis

  shelf-front:
    image: fdooch/shelf-front:0.1.0-alpha.7
    environment:
      - API_BASE_URL=http://localhost:8001
    ports:
      - "8181:80"
    depends_on:
      - shelf-back

  edgedb:
    image: edgedb/edgedb:2.5
    environment:
      - EDGEDB_SERVER_USER=edgedb
      - EDGEDB_PASSWORD=root
      - EDGEDB_SERVER_TLS_CERT_FILE=/certs/edbtlscert.dev.pem
      - EDGEDB_SERVER_TLS_KEY_FILE=/certs/edbprivkey.dev.pem
    volumes:
      - dbvolume:/var/lib/edgedb/data
      - ./certs:/certs
    ports:
      - "5656:5656"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  dbvolume: {}
```

Env file
```
APP_SECRET_KEY=732871
CELERY_BACKEND_DSN=redis://redis:6379
CELERY_BROKER_DSN=redis://redis:6379
CORS_ALLOW_ORIGINS=http://localhost:8181
DATABASE_DSN=edgedb://edgedb:root@edgedb:5656/edgedb
DATABASE_TLS_CA_FILE=/usr/src/shelf-back/certs/edbtlscert.dev.pem
STORAGE_LOCATION=/usr/src/shelf-data
```
